import $ from './jquery-global';
import 'datatables.net';
import 'datatables.net-responsive';
import './sweetalert';
import './phone-mask';
import './party';
import './shipper-bp';
import './purchase-invoice-grid';
import './container-activity-details-grid';
import './booking-details';
import './booking-equipment-grid';
import './booking-revenue-grid';
import './booking-cost-grid';
import './booking-totals';
import './container-purchase-tabs';
